package com.resumeai.auth.service;

import com.resumeai.auth.dto.AuthDtos.AuthResponse;
import com.resumeai.auth.dto.AuthDtos.ForgotPasswordRequest;
import com.resumeai.auth.dto.AuthDtos.LoginRequest;
import com.resumeai.auth.dto.AuthDtos.MessageResponse;
import com.resumeai.auth.dto.AuthDtos.PasswordChangeRequest;
import com.resumeai.auth.dto.AuthDtos.ProfileUpdateRequest;
import com.resumeai.auth.dto.AuthDtos.RegisterRequest;
import com.resumeai.auth.dto.AuthDtos.ResetPasswordRequest;
import com.resumeai.auth.dto.AuthDtos.RoleUpdateRequest;
import com.resumeai.auth.dto.AuthDtos.SubscriptionUpdateRequest;
import com.resumeai.auth.dto.AuthDtos.TokenRefreshRequest;
import com.resumeai.auth.model.User;
import com.resumeai.auth.repository.UserRepository;
import com.resumeai.auth.security.JwtUtil;
import jakarta.annotation.PostConstruct;
import java.io.IOException;
import java.net.MalformedURLException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.SecureRandom;
import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.core.io.UrlResource;
import org.springframework.http.HttpStatus;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ResponseStatusException;

/**
 * Core auth business logic.
 *
 * <p>Passwords are BCrypt-hashed via Spring Security's {@link PasswordEncoder}.
 * Access tokens are signed JWTs generated by {@link JwtUtil}.
 * Refresh tokens are opaque UUIDs stored in-memory (stateful fallback;
 * replace with Redis or DB in production).
 */
@Service
@Slf4j
public class AuthServiceImpl implements AuthService {
    private static final String ROLE_ADMIN = "ADMIN";
    private static final String ROLE_USER = "USER";
    private static final String PLAN_FREE = "FREE";
    private static final String PLAN_PREMIUM = "PREMIUM";
    private final UserRepository userRepository;
    private final PasswordResetEmailService passwordResetEmailService;
    private final AdminNotificationClient adminNotificationClient;
    private final AsyncNotificationService asyncNotificationService;
    private final PasswordEncoder passwordEncoder;
    private final JwtUtil jwtUtil;
    private final ObjectProvider<StringRedisTemplate> redisTemplateProvider;

    @Autowired
    public AuthServiceImpl(UserRepository userRepository,
                           PasswordResetEmailService passwordResetEmailService,
                           AdminNotificationClient adminNotificationClient,
                           AsyncNotificationService asyncNotificationService,
                           PasswordEncoder passwordEncoder,
                           JwtUtil jwtUtil,
                           ObjectProvider<StringRedisTemplate> redisTemplateProvider) {
        this.userRepository = userRepository;
        this.passwordResetEmailService = passwordResetEmailService;
        this.adminNotificationClient = adminNotificationClient;
        this.asyncNotificationService = asyncNotificationService;
        this.passwordEncoder = passwordEncoder;
        this.jwtUtil = jwtUtil;
        this.redisTemplateProvider = redisTemplateProvider;
    }

    AuthServiceImpl(UserRepository userRepository,
                    PasswordResetEmailService passwordResetEmailService,
                    AdminNotificationClient adminNotificationClient,
                    AsyncNotificationService asyncNotificationService,
                    PasswordEncoder passwordEncoder,
                    JwtUtil jwtUtil) {
        this(userRepository, passwordResetEmailService, adminNotificationClient,
                asyncNotificationService, passwordEncoder, jwtUtil, null);
    }

    /** refresh-token → userId map (in-memory; swap with Redis for production). */
    private final Map<String, Long> refreshTokenStore = new ConcurrentHashMap<>();
    private final Map<String, PasswordResetToken> passwordResetTokens = new ConcurrentHashMap<>();
    private static final SecureRandom OTP_RANDOM = new SecureRandom();

    @Value("${app.auth.reset-password.base-url:http://localhost:3000/reset-password}")
    private String resetPasswordBaseUrl;

    @Value("${app.auth.reset-password.expiry-minutes:10}")
    private long resetPasswordExpiryMinutes;

    @Value("${app.profile-pictures.storage-dir:uploads/profile-pictures}")
    private String profilePictureStorageDir;

    @Value("${app.profile-pictures.public-base-url:http://localhost:8090}")
    private String profilePicturePublicBaseUrl;

    @Value("${app.profile-pictures.max-bytes:5242880}")
    private long profilePictureMaxBytes;

    @Value("${app.bootstrap-admin.enabled:false}")
    private boolean bootstrapAdminEnabled;

    @Value("${app.bootstrap-admin.email:}")
    private String bootstrapAdminEmail;

    @Value("${app.bootstrap-admin.password:}")
    private String bootstrapAdminPassword;

    @Value("${app.protected-admin-email:}")
    private String protectedAdminEmail;

    // -------------------------------------------------------------------------
    // Seed
    // -------------------------------------------------------------------------

    @PostConstruct
    void init() {
        seedAdmin();
    }

    // -------------------------------------------------------------------------
    // Auth operations
    // -------------------------------------------------------------------------

    @Override
    public AuthResponse register(RegisterRequest request) {
        String email = normalizeEmail(request.email());
        if (userRepository.findByEmail(email).isPresent()) {
            throw new ResponseStatusException(HttpStatus.CONFLICT, "Email already registered");
        }
        User user = new User();
        user.setFullName(request.fullName().trim());
        user.setEmail(email);
        user.setPasswordHash(passwordEncoder.encode(request.password()));
        user.setPhone(request.phone());
        user.setRole(ROLE_USER);
        user.setProvider(defaultIfBlank(request.provider(), "LOCAL"));
        user.setSubscriptionPlan(PLAN_FREE);
        user.setActive(true);
        try {
            userRepository.save(user);
        } catch (DataIntegrityViolationException ex) {
            throw new ResponseStatusException(HttpStatus.CONFLICT, "Email already registered", ex);
        }
        // Fire-and-forget: welcome email + notification run on a background thread
        // so they never delay or fail the HTTP response even if a downstream
        // service (notification-service, SMTP) is slow or temporarily unavailable.
        asyncNotificationService.sendWelcomeNotificationsAsync(user);
        asyncNotificationService.notifyAdminsOfNewRegistrationAsync(user);
        return buildAuthResponse(user);
    }

    @Override
    public AuthResponse login(LoginRequest request) {
        User user = userRepository.findByEmail(normalizeEmail(request.email()))
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Invalid credentials"));
        if (!user.isActive()) {
            throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Account is inactive");
        }
        if (!passwordEncoder.matches(request.password(), user.getPasswordHash())) {
            throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Invalid credentials");
        }
        return buildAuthResponse(user);
    }

    @Override
    public AuthResponse createSession(User user) {
        if (user == null || !user.isActive()) {
            throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Account is inactive");
        }
        return buildAuthResponse(user);
    }

    @Override
    public MessageResponse logout(TokenRefreshRequest request) {
        refreshTokenStore.remove(request.refreshToken());
        return new MessageResponse("Logged out successfully.");
    }

    @Override
    public AuthResponse refresh(TokenRefreshRequest request) {
        Long userId = refreshTokenStore.get(request.refreshToken());
        if (userId == null) {
            throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Invalid or expired refresh token");
        }
        return buildAuthResponse(getUserById(userId));
    }

    @Override
    public MessageResponse requestPasswordReset(ForgotPasswordRequest request) {
        userRepository.findByEmail(normalizeEmail(request.email()))
                .filter(User::isActive)
                .ifPresent(user -> {
                    clearPasswordResetTokens(user.getUserId());
                    String otp = generateOtp();
                    String token = passwordResetOtpKey(user.getEmail(), otp);
                    Instant expiresAt = Instant.now().plus(Duration.ofMinutes(resetPasswordExpiryMinutes));
                    storePasswordResetToken(token, user.getUserId(), expiresAt);
                    passwordResetEmailService.sendPasswordResetOtp(
                            user.getEmail(), user.getFullName(), otp, resetPasswordExpiryMinutes);
                });
        return new MessageResponse("If the email is registered, a password reset OTP has been sent.");
    }

    @Override
    public MessageResponse resetPassword(ResetPasswordRequest request) {
        String email = normalizeEmail(request.email());
        PasswordResetToken resetToken = findPasswordResetToken(passwordResetOtpKey(email, request.otp()));
        if (resetToken == null || resetToken.isExpired()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "OTP is invalid or expired");
        }
        User user = getUserById(resetToken.userId());
        if (!user.isActive()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "User account is inactive");
        }
        if (!user.getEmail().equalsIgnoreCase(email)) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "OTP is invalid or expired");
        }
        user.setPasswordHash(passwordEncoder.encode(request.newPassword()));
        userRepository.save(user);
        clearPasswordResetTokens(user.getUserId());
        return new MessageResponse("Password has been reset successfully.");
    }

    // -------------------------------------------------------------------------
    // Profile & account management
    // -------------------------------------------------------------------------

    @Override
    public User getUserById(Long userId) {
        return userRepository.findById(userId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "User not found"));
    }

    @Override
    public List<User> getAllUsers() {
        return userRepository.findAll();
    }

    @Override
    public User updateProfile(Long userId, ProfileUpdateRequest request) {
        User user = getUserById(userId);
        if (request.fullName() != null && !request.fullName().isBlank()) {
            user.setFullName(request.fullName());
        }
        if (request.phone() != null && !request.phone().isBlank()) {
            user.setPhone(request.phone());
        }
        if (request.pictureUrl() != null) {
            user.setPictureUrl(request.pictureUrl().isBlank() ? null : request.pictureUrl());
        }
        return userRepository.save(user);
    }

    @Override
    public User uploadProfilePicture(Long userId, MultipartFile file) {
        User user = getUserById(userId);
        validateProfilePicture(file);

        String extension = profilePictureExtension(file);
        String fileName = "user-" + userId + "-" + UUID.randomUUID() + extension;
        Path storageDir = profilePictureStoragePath();
        Path target = storageDir.resolve(fileName).normalize();
        if (!target.startsWith(storageDir)) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid profile picture file name");
        }

        try (var in = file.getInputStream()) {
            Files.createDirectories(storageDir);
            Files.copy(in, target, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException ex) {
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,
                    "Could not save profile picture", ex);
        }

        user.setPictureUrl(profilePictureUrl(fileName));
        return userRepository.save(user);
    }

    @Override
    public Resource loadProfilePicture(String fileName) {
        String cleanFileName = StringUtils.cleanPath(fileName == null ? "" : fileName);
        if (cleanFileName.isBlank() || cleanFileName.contains("..")) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid profile picture file name");
        }

        Path storageDir = profilePictureStoragePath();
        Path file = storageDir.resolve(cleanFileName).normalize();
        if (!file.startsWith(storageDir) || !Files.exists(file) || !Files.isRegularFile(file)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Profile picture not found");
        }

        try {
            Resource resource = new UrlResource(file.toUri());
            if (!resource.exists() || !resource.isReadable()) {
                throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Profile picture not found");
            }
            return resource;
        } catch (MalformedURLException ex) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid profile picture path", ex);
        }
    }

    @Override
    public User changePassword(Long userId, PasswordChangeRequest request) {
        User user = getUserById(userId);
        if (!passwordEncoder.matches(request.currentPassword(), user.getPasswordHash())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Current password does not match");
        }
        user.setPasswordHash(passwordEncoder.encode(request.newPassword()));
        clearPasswordResetTokens(userId);
        return userRepository.save(user);
    }

    @Override
    public User updateSubscription(Long userId, SubscriptionUpdateRequest request) {
        User user = getUserById(userId);
        String previousPlan = user.getSubscriptionPlan();
        String nextPlan = normalizePlan(request.subscriptionPlan());
        user.setSubscriptionPlan(nextPlan);
        userRepository.save(user);
        if (previousPlan == null || !previousPlan.equalsIgnoreCase(nextPlan)) {
            sendPlanUpdatedEmail(user);
        }
        adminNotificationClient.notifyPlanChange(user, user.getSubscriptionPlan());
        return user;
    }

    @Override
    public User updateRole(Long userId, RoleUpdateRequest request) {
        User user = getUserById(userId);
        ensureNotProtectedAdmin(user, "Protected admin role cannot be changed");
        user.setRole(normalizeRole(request.role()));
        if (ROLE_ADMIN.equalsIgnoreCase(user.getRole())) {
            user.setSubscriptionPlan(PLAN_PREMIUM);
        }
        return userRepository.save(user);
    }

    @Override
    public User deactivateAccount(Long userId) {
        User user = getUserById(userId);
        ensureNotProtectedAdmin(user, "Protected admin cannot be deactivated");
        user.setActive(false);
        User saved = userRepository.save(user);
        sendAccountDeactivatedEmail(saved);
        return saved;
    }

    @Override
    public User reactivateAccount(Long userId) {
        User user = getUserById(userId);
        user.setActive(true);
        return userRepository.save(user);
    }

    @Override
    public void deleteAccount(Long userId) {
        User user = getUserById(userId); // throws 404 if missing
        ensureNotProtectedAdmin(user, "Protected admin cannot be deleted");
        clearPasswordResetTokens(userId);
        refreshTokenStore.entrySet().removeIf(entry -> entry.getValue().equals(userId));
        userRepository.deleteById(userId);
        log.info("Deleted user {} ({}) from auth database", userId, user.getEmail());
    }

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    private AuthResponse buildAuthResponse(User user) {
        String accessToken  = jwtUtil.generateToken(
                user.getUserId(), user.getEmail(), user.getRole(), user.getSubscriptionPlan());
        String refreshToken = "refresh-" + UUID.randomUUID();
        refreshTokenStore.put(refreshToken, user.getUserId());
        return new AuthResponse(user, accessToken, refreshToken);
    }

    private void ensureNotProtectedAdmin(User user, String message) {
        if (isProtectedAdmin(user)) {
            throw new ResponseStatusException(HttpStatus.FORBIDDEN, message);
        }
    }

    private boolean isProtectedAdmin(User user) {
        return user != null
                && protectedAdminEmail != null
                && !protectedAdminEmail.isBlank()
                && protectedAdminEmail.equalsIgnoreCase(user.getEmail())
                && ROLE_ADMIN.equalsIgnoreCase(user.getRole());
    }

    private void seedAdmin() {
        if (!bootstrapAdminEnabled) {
            return;
        }
        if (bootstrapAdminEmail == null || bootstrapAdminEmail.isBlank()
                || bootstrapAdminPassword == null || bootstrapAdminPassword.isBlank()) {
            throw new IllegalStateException(
                    "Bootstrap admin is enabled, but APP_BOOTSTRAP_ADMIN_EMAIL or APP_BOOTSTRAP_ADMIN_PASSWORD is missing");
        }
        String email = normalizeEmail(bootstrapAdminEmail);
        if (userRepository.findByEmail(email).isPresent()) {
            return;
        }
        User admin = new User();
        admin.setFullName("ResumeAI Admin");
        admin.setEmail(email);
        admin.setPasswordHash(passwordEncoder.encode(bootstrapAdminPassword));
        admin.setPhone("0000000000");
        admin.setRole(ROLE_ADMIN);
        admin.setProvider("LOCAL");
        admin.setSubscriptionPlan(PLAN_PREMIUM);
        admin.setActive(true);
        userRepository.save(admin);
    }

    private String generateOtp() {
        return String.format("%06d", OTP_RANDOM.nextInt(1_000_000));
    }

    private String passwordResetOtpKey(String email, String otp) {
        String normalizedEmail = normalizeEmail(email);
        String normalizedOtp = otp == null ? "" : otp.trim();
        return normalizedEmail + ":" + normalizedOtp;
    }

    private String normalizeEmail(String email) {
        return email == null ? "" : email.trim().toLowerCase(Locale.ROOT);
    }

    private void clearPasswordResetTokens(Long userId) {
        passwordResetTokens.entrySet().removeIf(e -> e.getValue().userId().equals(userId));
        StringRedisTemplate redisTemplate = redis();
        if (redisTemplate == null) {
            return;
        }
        try {
            String userKey = passwordResetUserKey(userId);
            String token = redisTemplate.opsForValue().get(userKey);
            if (token != null && !token.isBlank()) {
                redisTemplate.delete(passwordResetKey(token));
            }
            redisTemplate.delete(userKey);
        } catch (RuntimeException ex) {
            log.debug("Redis reset-token cleanup skipped for user {}: {}", userId, ex.getMessage());
        }
    }

    private void storePasswordResetToken(String token, Long userId, Instant expiresAt) {
        PasswordResetToken resetToken = new PasswordResetToken(userId, expiresAt);
        passwordResetTokens.put(token, resetToken);
        StringRedisTemplate redisTemplate = redis();
        if (redisTemplate == null) {
            return;
        }
        try {
            String previousToken = redisTemplate.opsForValue().get(passwordResetUserKey(userId));
            if (previousToken != null && !previousToken.isBlank()) {
                redisTemplate.delete(passwordResetKey(previousToken));
            }
            long ttlSeconds = Math.max(1, Duration.between(Instant.now(), expiresAt).toSeconds());
            redisTemplate.opsForValue().set(passwordResetKey(token),
                    userId + ":" + expiresAt.toEpochMilli(), ttlSeconds, TimeUnit.SECONDS);
            redisTemplate.opsForValue().set(passwordResetUserKey(userId),
                    token, ttlSeconds, TimeUnit.SECONDS);
        } catch (RuntimeException ex) {
            log.warn("Redis reset-token store unavailable; using in-memory fallback: {}", ex.getMessage());
        }
    }

    private PasswordResetToken findPasswordResetToken(String token) {
        StringRedisTemplate redisTemplate = redis();
        if (redisTemplate != null) {
            try {
                String raw = redisTemplate.opsForValue().get(passwordResetKey(token));
                if (raw != null && !raw.isBlank()) {
                    String[] parts = raw.split(":", 2);
                    return new PasswordResetToken(Long.valueOf(parts[0]),
                            Instant.ofEpochMilli(Long.parseLong(parts[1])));
                }
            } catch (RuntimeException ex) {
                log.debug("Redis reset-token lookup skipped: {}", ex.getMessage());
            }
        }
        return passwordResetTokens.get(token);
    }

    private StringRedisTemplate redis() {
        return redisTemplateProvider == null ? null : redisTemplateProvider.getIfAvailable();
    }

    private String passwordResetKey(String token) {
        return "auth:password-reset:token:" + token;
    }

    private String passwordResetUserKey(Long userId) {
        return "auth:password-reset:user:" + userId;
    }

    private void sendAccountDeactivatedEmail(User user) {
        try {
            passwordResetEmailService.sendAccountDeactivatedEmail(user.getEmail(), user.getFullName());
        } catch (RuntimeException ex) {
            log.warn("Account deactivation email could not be sent to {}: {}", user.getEmail(), ex.getMessage());
        }
    }

    private void sendPlanUpdatedEmail(User user) {
        try {
            passwordResetEmailService.sendPlanUpdatedEmail(
                    user.getEmail(), user.getFullName(), user.getSubscriptionPlan());
        } catch (RuntimeException ex) {
            log.warn("Plan update email could not be sent to {}: {}", user.getEmail(), ex.getMessage());
        }
    }

    private String defaultIfBlank(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }

    private String normalizePlan(String plan) {
        if (!PLAN_FREE.equalsIgnoreCase(plan) && !PLAN_PREMIUM.equalsIgnoreCase(plan)) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Subscription plan must be FREE or PREMIUM");
        }
        return plan.toUpperCase();
    }

    private String normalizeRole(String role) {
        if (!ROLE_USER.equalsIgnoreCase(role) && !ROLE_ADMIN.equalsIgnoreCase(role)) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Role must be USER or ADMIN");
        }
        return role.toUpperCase();
    }

    private void validateProfilePicture(MultipartFile file) {
        if (file == null || file.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Profile picture file is required");
        }
        if (file.getSize() > profilePictureMaxBytes) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Profile picture must be 5 MB or smaller");
        }
        String contentType = file.getContentType() == null ? "" : file.getContentType().toLowerCase();
        if (!List.of("image/jpeg", "image/png", "image/webp", "image/gif").contains(contentType)) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "Profile picture must be a JPG, PNG, WEBP, or GIF image");
        }
    }

    private String profilePictureExtension(MultipartFile file) {
        String originalFileName = StringUtils.cleanPath(file.getOriginalFilename() == null
                ? ""
                : file.getOriginalFilename());
        String extension = "";
        int dot = originalFileName.lastIndexOf('.');
        if (dot >= 0 && dot < originalFileName.length() - 1) {
            extension = originalFileName.substring(dot).toLowerCase();
        }
        if (List.of(".jpg", ".jpeg", ".png", ".webp", ".gif").contains(extension)) {
            return extension;
        }
        return switch (file.getContentType() == null ? "" : file.getContentType().toLowerCase()) {
            case "image/png" -> ".png";
            case "image/webp" -> ".webp";
            case "image/gif" -> ".gif";
            default -> ".jpg";
        };
    }

    private Path profilePictureStoragePath() {
        return Path.of(profilePictureStorageDir).toAbsolutePath().normalize();
    }

    private String profilePictureUrl(String fileName) {
        String baseUrl = profilePicturePublicBaseUrl == null ? "" : profilePicturePublicBaseUrl.strip();
        if (baseUrl.endsWith("/")) {
            baseUrl = baseUrl.substring(0, baseUrl.length() - 1);
        }
        return baseUrl + "/api/v1/auth/profile-picture/" + fileName;
    }

    private record PasswordResetToken(Long userId, Instant expiresAt) {
        private boolean isExpired() {
            return Instant.now().isAfter(expiresAt);
        }
    }
}
