package com.resumeai.jobmatch.model;

import jakarta.persistence.*;
import java.time.Instant;
import lombok.Data;

@Entity
@Table(name = "job_matches",
       indexes = {
           @Index(name = "idx_jm_user",       columnList = "userId"),
           @Index(name = "idx_jm_resume",     columnList = "resumeId"),
           @Index(name = "idx_jm_source",     columnList = "source"),
           @Index(name = "idx_jm_bookmarked", columnList = "bookmarked"),
           @Index(name = "idx_jm_retention",  columnList = "bookmarked, matchedAt")
       })
@Data
public class JobMatch {

    /** UUID generated by service before persist. */
    @Id
    @Column(length = 36)
    private String matchId;

    @Column(nullable = false)
    private Long resumeId;

    @Column(nullable = false)
    private Long userId;

    @Column(nullable = false, length = 255)
    private String jobTitle;

    @Column(columnDefinition = "TEXT")
    private String jobDescription;

    @Column(nullable = false)
    private int matchScore;

    @Column(columnDefinition = "TEXT")
    private String missingSkills;

    @Column(columnDefinition = "TEXT")
    private String recommendations;

    @Column(nullable = false, length = 50)
    private String source;

    @Column(length = 2048)
    private String applyUrl;

    @Column(nullable = false)
    private Instant matchedAt;

    @Column(nullable = false)
    private boolean bookmarked;
}
