package com.resumeai.export.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import java.time.Instant;
import lombok.Data;

@Entity
@Table(name = "export_jobs",
       indexes = {
           @Index(name = "idx_export_user",   columnList = "userId"),
           @Index(name = "idx_export_status", columnList = "status"),
           @Index(name = "idx_export_expires", columnList = "expiresAt")
       })
@Data
public class ExportJob {

    /** UUID generated by service before persist — no auto-increment. */
    @Id
    @Column(length = 36)
    private String jobId;

    @Column(nullable = false)
    private Long resumeId;

    @Column(nullable = false)
    private Long userId;

    @Column(nullable = false, length = 20)
    private String format;

    @Column(nullable = false, length = 50)
    private String status;

    /** API download URL, backed by file bytes stored in this SQL row. */
    @Column(length = 1024)
    private String fileUrl;

    @Column(length = 255)
    private String fileName;

    @Column(length = 150)
    private String contentType;

    @JsonIgnore
    @Lob
    @Column(columnDefinition = "LONGBLOB")
    private byte[] fileContent;

    @Column
    private int fileSizeKb;

    @Column(nullable = false)
    private Instant requestedAt;

    @Column
    private Instant completedAt;

    @Column
    private Instant expiresAt;

    @Column
    private Long templateId;

    @Column(columnDefinition = "TEXT")
    private String customizations;
}
