package com.resumeai.notification.model;

import jakarta.persistence.*;
import java.time.Instant;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

@Entity
@Table(name = "notifications",
       indexes = {
           @Index(name = "idx_notif_recipient", columnList = "recipientId"),
           @Index(name = "idx_notif_read",      columnList = "`read`"),
           @Index(name = "idx_notif_channel",   columnList = "channel")
       })
@Data
public class Notification {

    /** UUID generated by service before persist. */
    @Id
    @Column(length = 36)
    private String notificationId;

    @Column(nullable = false)
    private Long recipientId;

    @Column(nullable = false, length = 100)
    private String type;

    @Column(nullable = false, length = 255)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String message;

    @Column(nullable = false, length = 50)
    private String channel;

    @Column(length = 100)
    private String relatedId;

    @Column(length = 100)
    private String relatedType;

    @Column(length = 1024)
    private String actionUrl;

    @Column(length = 255)
    private String recipientEmail;

    @Column(name = "`read`", nullable = false)
    private boolean readStatus;

    @Column(nullable = false)
    private Instant sentAt;

    @JsonProperty("read")
    public boolean isRead() {
        return readStatus;
    }

    @JsonProperty("read")
    public void setRead(boolean read) {
        this.readStatus = read;
    }
}
